"""initial migration

Revision ID: 46b02c5591b6
Revises: 
Create Date: 2022-03-13 15:00:56.138200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b02c5591b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scorerecord', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scorerecord', 'user', ['user_id'], ['id'])
    op.add_column('userProgress', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('userProgress', sa.Column('character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userProgress', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userProgress', 'characters', ['character_id'], ['id'])
    op.add_column('userTestCharacterResult', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('userTestCharacterResult', sa.Column('character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userTestCharacterResult', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userTestCharacterResult', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userTestCharacterResult', type_='foreignkey')
    op.drop_constraint(None, 'userTestCharacterResult', type_='foreignkey')
    op.drop_column('userTestCharacterResult', 'character_id')
    op.drop_column('userTestCharacterResult', 'user_id')
    op.drop_constraint(None, 'userProgress', type_='foreignkey')
    op.drop_constraint(None, 'userProgress', type_='foreignkey')
    op.drop_column('userProgress', 'character_id')
    op.drop_column('userProgress', 'user_id')
    op.drop_constraint(None, 'scorerecord', type_='foreignkey')
    op.drop_column('scorerecord', 'user_id')
    # ### end Alembic commands ###
